Numpy arrays vs python lists


In [1]:
#speed list

a = [i for i in range(1000000)]
b = [i for i in range(1000000)]

c = []
import time
start = time.time()
for i in range(1000000):
    c.append(a[i] + b[i])
print("Time taken for list append:", time.time() - start)

Time taken for list append: 0.04763531684875488


In [2]:
import numpy as np
a = np.arange(1000000)
b = np.arange(1000000)

start = time.time()
c = a + b
print("Time taken for numpy array addition:", time.time() - start)

Time taken for numpy array addition: 0.00993204116821289


In [3]:
# memory usage
import sys
a = [i for i in range(1000000)]
sys.getsizeof(a)

8448728

In [5]:
a= np.arange(1000000, dtype=np.int32)
sys.getsizeof(a)

4000112

In [6]:
#Fancy Indexing
a = np.arange(12).reshape(4, 3)

# we can directly pass a list of indices
a[[0,2,3]]

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [7]:
a[:,[1,2]] #if we are using 2D array, we can pass a list of indices for each axis and this is for columns

array([[ 1,  2],
       [ 4,  5],
       [ 7,  8],
       [10, 11]])

In [10]:
a = np.random.randint(1,100,24).reshape(6,4)
a

array([[50, 70, 46,  9],
       [38, 95, 12, 71],
       [62, 78, 65, 53],
       [68, 30, 80, 11],
       [74, 97, 44, 85],
       [49, 71, 41, 41]])

In [ ]:
#find all the elements greater than 50
a >50 #the result is a boolean array

array([[False,  True, False, False],
       [False,  True, False,  True],
       [ True,  True,  True,  True],
       [ True, False,  True, False],
       [ True,  True, False,  True],
       [False,  True, False, False]])

In [12]:
a[a>50] #this will give us all the elements greater than 50 and rest will be discarded

array([70, 95, 71, 62, 78, 65, 53, 68, 80, 74, 97, 85, 71])

In [13]:
#find all even number 

a[a%2==0] #this will give us all the even numbers and rest will be discarded

array([50, 70, 46, 38, 12, 62, 78, 68, 30, 80, 74, 44])

& is a bitwise and we use with boolean AND is the and 

In [15]:
a[(a>50) & (a%2==0)] #this will give us all the even numbers greater than 50 and rest will be discarded

array([70, 62, 78, 68, 80, 74])

In [17]:
#find all the number divisible by 7
a[a%7==0] #this will give us all the numbers divisible by 7 and rest will be discarded

array([70, 49])

Broadcasting : describes how numpy treats arrays with different shapes during arithmatic operation
the smaller array is broadcasted accross the larger array so that they have compatible shapes

In [18]:
a = np.arange(12).reshape(4, 3)
b = np.arange(12).reshape(4, 3)
a + b #this will give us the element wise addition of the two arrays

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22]])

In [20]:
a = np.arange(6).reshape(2, 3)
b = np.arange(3).reshape(1, 3)
print(a)
print(b)

a + b #this will give us the element wise addition of the two arrays

[[0 1 2]
 [3 4 5]]
[[0 1 2]]


array([[0, 2, 4],
       [3, 5, 7]])

In [22]:
#Working with mathematical formulas
#finding the root mean square

actual = np.random.randint(1,100,25)
predicted = np.random.randint(1,100,25)

def rmse(actual, predicted):
    return np.sqrt(np.mean((actual - predicted) ** 2))
np.random.randint(1,100,25)

array([74, 79, 33, 62, 21, 38, 85, 99, 24,  3, 64, 87, 31, 16, 92,  7,  8,
       51, 40, 35, 39, 68, 80, 79, 36])

In [29]:
#dealing with missing values none is not a missing value but np.nan is a missing value
a = np.array([1, 2, 3, np.nan, 5])
np.isnan(a) #this will give us a boolean array with True for missing values and False for non missing values
a[np.isnan(a)] #this will give us all the missing values

array([nan])

In [30]:
 #this will give us all the missing values and rest will be discarded