In [1]:
#Sorting using numpy

import numpy as np
a = np.random.randint(1, 100, 30)

np.sort(a)

array([ 2,  2,  5,  8, 10, 12, 20, 23, 25, 28, 29, 33, 35, 37, 46, 52, 56,
       57, 59, 61, 66, 69, 78, 81, 83, 86, 89, 93, 97, 99])

In [2]:
b = np.random.randint(1, 100, 30).reshape(5, 6)
b 

array([[74, 36, 81, 22, 85, 69],
       [86, 32, 45, 11, 95,  4],
       [ 8, 69, 94, 22, 33, 62],
       [89, 36, 67, 72, 37, 54],
       [46, 24, 96, 61, 19, 21]])

In [ ]:
np.sort(b, axis=0) # sort by columm

array([[ 8, 24, 45, 11, 19,  4],
       [46, 32, 67, 22, 33, 21],
       [74, 36, 81, 22, 37, 54],
       [86, 36, 94, 61, 85, 62],
       [89, 69, 96, 72, 95, 69]])

In [4]:
np.sort(b, axis=1) # sort by row

array([[22, 36, 69, 74, 81, 85],
       [ 4, 11, 32, 45, 86, 95],
       [ 8, 22, 33, 62, 69, 94],
       [36, 37, 54, 67, 72, 89],
       [19, 21, 24, 46, 61, 96]])

In [5]:
#append appneds the values to the end of the array
np.append(b, [[1, 2, 3, 4, 5, 6]], axis=0) # append to the end of the array

array([[74, 36, 81, 22, 85, 69],
       [86, 32, 45, 11, 95,  4],
       [ 8, 69, 94, 22, 33, 62],
       [89, 36, 67, 72, 37, 54],
       [46, 24, 96, 61, 19, 21],
       [ 1,  2,  3,  4,  5,  6]])

In [6]:
np.append(a, [1, 2, 3, 4, 5, 6]) # append to the end of the array

array([66, 97, 35, 33, 93, 52, 86, 83,  2, 10, 69, 12,  8, 23, 56,  5, 28,
       46,  2, 25, 61, 59, 89, 29, 81, 78, 20, 99, 37, 57,  1,  2,  3,  4,
        5,  6])

In [7]:
#concatenate concatenates the values to the end of the array
np.concatenate((b, [[1, 2, 3, 4, 5, 6]]), axis=0) # append to the end of the array

array([[74, 36, 81, 22, 85, 69],
       [86, 32, 45, 11, 95,  4],
       [ 8, 69, 94, 22, 33, 62],
       [89, 36, 67, 72, 37, 54],
       [46, 24, 96, 61, 19, 21],
       [ 1,  2,  3,  4,  5,  6]])

In [9]:
#concatenate concatenates the values to the end of the array
np.concatenate((a, [1, 2, 3, 4, 5, 6]), axis=0) # append to the end of the array

array([66, 97, 35, 33, 93, 52, 86, 83,  2, 10, 69, 12,  8, 23, 56,  5, 28,
       46,  2, 25, 61, 59, 89, 29, 81, 78, 20, 99, 37, 57,  1,  2,  3,  4,
        5,  6])

In [11]:
#unique returns the unique values in the array
np.unique(a) # unique values in the array


array([ 2,  5,  8, 10, 12, 20, 23, 25, 28, 29, 33, 35, 37, 46, 52, 56, 57,
       59, 61, 66, 69, 78, 81, 83, 86, 89, 93, 97, 99])

In [12]:
np.unique(b) # unique values in the array

array([ 4,  8, 11, 19, 21, 22, 24, 32, 33, 36, 37, 45, 46, 54, 61, 62, 67,
       69, 72, 74, 81, 85, 86, 89, 94, 95, 96])

In [13]:
#expanddims adds a new axis to the array
np.expand_dims(a, axis=0) # add a new axis to the array

array([[66, 97, 35, 33, 93, 52, 86, 83,  2, 10, 69, 12,  8, 23, 56,  5,
        28, 46,  2, 25, 61, 59, 89, 29, 81, 78, 20, 99, 37, 57]])

In [14]:
#where returns the indices of the values that are True
np.where(a > 50) # indices of the values that are greater than 50

(array([ 0,  1,  4,  5,  6,  7, 10, 14, 20, 21, 22, 24, 25, 27, 29]),)

In [15]:
np.where(a>50, a, 0) # indices of the values that are greater than 50

array([66, 97,  0,  0, 93, 52, 86, 83,  0,  0, 69,  0,  0,  0, 56,  0,  0,
        0,  0,  0, 61, 59, 89,  0, 81, 78,  0, 99,  0, 57])

In [16]:
#argmax returns the index of the maximum value in the array
np.argmax(a) # index of the maximum value in the array

27

In [17]:
np.argmin(b) # index of the minimum value in the array

11

In [18]:
# np.cumsum returns the cumulative sum of the array
np.cumsum(a) # cumulative sum of the array

array([  66,  163,  198,  231,  324,  376,  462,  545,  547,  557,  626,
        638,  646,  669,  725,  730,  758,  804,  806,  831,  892,  951,
       1040, 1069, 1150, 1228, 1248, 1347, 1384, 1441])

In [19]:
#cumprod returns the cumulative product of the array
np.cumprod(a) # cumulative product of the array

array([                  66,                 6402,               224070,
                    7394310,            687670830,          35758883160,
              3075263951760,      255246907996080,      510493815992160,
           5104938159921600,   352240733034590400,  4226888796415084800,
       -3078377776098424832,  2984287444574435328,  1099400232782413824,
        5497001163912069120,  6342079999861522432, -3412225185722793984,
       -6824450371445587968, -4590562622753734656, -3323158882334539776,
        6847810753067220992,   712602590567464960,  2218731052746932224,
       -4750225464594006016, -1582704764141436928,  5239392864590364672,
        2191059530578657280,  7282226336572112896, -9188212510709252096])

In [20]:
np.cumsum(b,axis=0) # cumulative sum of the array

array([[ 74,  36,  81,  22,  85,  69],
       [160,  68, 126,  33, 180,  73],
       [168, 137, 220,  55, 213, 135],
       [257, 173, 287, 127, 250, 189],
       [303, 197, 383, 188, 269, 210]])

In [21]:
#np.percentile returns the percentile of the array
np.percentile(a, 50) # 50th percentile of the array

49.0

In [25]:
#np.histogram returns the histogram of the array (ferquency distribution)
np.histogram(a, bins=10) # histogram of the array

(array([5, 2, 4, 3, 1, 4, 3, 1, 4, 3]),
 array([ 2. , 11.7, 21.4, 31.1, 40.8, 50.5, 60.2, 69.9, 79.6, 89.3, 99. ]))

In [27]:
#np.corrcoef returns the correlation coefficient of the array
salary = np.random.randint(1, 100, 30)
age = np.random.randint(1, 100, 30)
np.corrcoef(salary, age) # correlation coefficient of the array

array([[1.        , 0.05345593],
       [0.05345593, 1.        ]])

In [29]:
#np.isin returns True if the value is in the array used to check multiples values if they are in the array
np.isin(a, [1, 2, 3, 4, 5]) # True if the value is in the array

array([False, False, False, False, False, False, False, False,  True,
       False, False, False, False, False, False,  True, False, False,
        True, False, False, False, False, False, False, False, False,
       False, False, False])

In [30]:
# np.flip flips the array
np.flip(a) # flips the array

array([57, 37, 99, 20, 78, 81, 29, 89, 59, 61, 25,  2, 46, 28,  5, 56, 23,
        8, 12, 69, 10,  2, 83, 86, 52, 93, 33, 35, 97, 66])

In [31]:
np.flip(b, axis=0) # flips the array

array([[46, 24, 96, 61, 19, 21],
       [89, 36, 67, 72, 37, 54],
       [ 8, 69, 94, 22, 33, 62],
       [86, 32, 45, 11, 95,  4],
       [74, 36, 81, 22, 85, 69]])

In [32]:
#np.put returns the array with the values replaced
np.put(a, [1, 2, 3], [4, 5, 6]) # replaces the values in the array

In [33]:
a

array([66,  4,  5,  6, 93, 52, 86, 83,  2, 10, 69, 12,  8, 23, 56,  5, 28,
       46,  2, 25, 61, 59, 89, 29, 81, 78, 20, 99, 37, 57])

In [ ]:
#np.delete deletes the values in the array
np.delete(a, [1, 2, 3]) # deletes the values in the array(indices are passed)

array([66, 93, 52, 86, 83,  2, 10, 69, 12,  8, 23, 56,  5, 28, 46,  2, 25,
       61, 59, 89, 29, 81, 78, 20, 99, 37, 57])