#LIST

In [1]:
fruits = ['apple', 'banana', 'cherry']
fruits

['apple', 'banana', 'cherry']

In [2]:
type(fruits)

list

In [3]:
fruits.append([1,2,True])
fruits

['apple', 'banana', 'cherry', [1, 2, True]]

In [4]:
fruits[-1][2]

True

In [5]:
fruits[-1][0:2]

[1, 2]

In [6]:
fruits

['apple', 'banana', 'cherry', [1, 2, True]]

In [7]:
fruits = fruits + ['banana']
fruits

['apple', 'banana', 'cherry', [1, 2, True], 'banana']

TUPLES are same as list but immutable we can change from tuple to list and list to tuple


"NUMPY"

In [8]:
import numpy as np

In [9]:
a = np.array([1, 2, 3])
type(a)

numpy.ndarray

In [10]:
b = np.array([[1, 2, 3], [4, 5, 6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
np.array([1,2,3], dtype=float)


array([1., 2., 3.])

In [12]:
#np.arange(10)
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [14]:
np.arange(1,11).reshape(2,5) # reshapes the array into 5 rows and 2 columns

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [15]:
np.ones((2,3)) # creates a 2x3 array of ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [16]:
np.zeros((2,3)) # creates a 2x3 array of zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
np.random.rand(3, 2)
# creates a 3x2 array of random numbers between 0 and 1
#np.random.randn(3, 2)
# creates a 3x2 array of random numbers from the standard normal distribution

array([[0.06788457, 0.41264885],
       [0.33836487, 0.90359609],
       [0.73984801, 0.71101391]])

In [18]:
np.linspace(0, 10, 5) # creates an array of 5 evenly spaced numbers between 0 and 1(lowerRange, upperRange, number of points) 

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [19]:
np.identity(3) # creates a 3x3 identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
b.ndim # number of dimensions of the array

2

In [21]:
b.shape # returns the shape of the array

(2, 3)

In [22]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
b.itemsize # returns the size of each element in bytes


8

In [24]:
b.dtype

dtype('int64')

Changing Datatype

In [25]:
b.astype(np.float32) # changes the data type of the array to float32

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

Array operations

In [26]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

In [27]:
#scalar operations
a1 * 2 #any kind of basic operation

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [28]:
#relatoinal operations

a1 > 5 # returns a boolean array

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

In [29]:
#vector operations : when two ndarrays are worked together
a1 + a2 # returns an array of the same shape as the two arrays

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [30]:
a1 * a2

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

In [31]:
np.max(a1) # returns the maximum value of the array

11

In [32]:
np.min(a1) # returns the minimum value of the array

0

In [33]:
np.sum(a1) # returns the sum of all elements in the array

66

In [34]:
np.prod(a1) # returns the product of all elements in the array

0

In [35]:
np.max(a1,axis=1) # returns the maximum value of the array for row we use axis 0 and for column we use axis 1

array([ 3,  7, 11])

Statistical options we can also have the flexibility of using the axis if we need to find the mean , median, std of a particular row or colummns


In [36]:
np.mean(a1) # returns the mean of all elements in the array

5.5

In [37]:
np.median(a1) # returns the median of all elements in the array

5.5

In [38]:
np.std(a1) # returns the standard deviation of all elements in the array

3.452052529534663

In [39]:
np.var(a1) # returns the variance of all elements in the array

11.916666666666666

In [40]:
#trigo
np.sin(a1) # returns the sine of all elements in the array

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849, -0.54402111, -0.99999021]])

In [41]:
np.log(a1) # returns the natural logarithm of all elements in the array

/var/folders/gm/nbsrp6ks1gnb1c4z3v9rvb4r0000gn/T/ipykernel_19332/1045684106.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(a1) # returns the natural logarithm of all elements in the array


array([[      -inf, 0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947, 1.94591015],
       [2.07944154, 2.19722458, 2.30258509, 2.39789527]])

In [42]:
np.exp(a1) # returns the exponential of all elements in the array

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04]])

In [44]:
np.round(np.random.randn(2,3)*100) # returns a 2x3 array of random numbers between 0 and 1

array([[  14., -112.,  -82.],
       [  75.,   21.,   46.]])

Indexing and Slicing

In [45]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [46]:
a1[-1]

9

In [47]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [48]:
a2[1,2]

6

In [49]:
# for 3d 
a3[1,0,1]

5

In [51]:
a1[2:5]

array([2, 3, 4])

In [ ]:
a2[0,:] #fetches all the columns of the first row

array([0, 1, 2, 3])

In [54]:
a2[:,2] # 3 columns of all rows

array([ 2,  6, 10])

In [55]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a2[1:,1:3] # 1th row onwards and 1th column on wards 

array([[ 5,  6],
       [ 9, 10]])

In [ ]:
a2[::2,1::2] # :2 for skipping the rows and columns alternatively

array([[ 1,  3],
       [ 9, 11]])

In [61]:
a3 = np.arange(27).reshape(3,3,3) # 3d array of 3x3x3
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [73]:
a3[0,1,:] #1st 2d array, 2nd row all columns


array([3, 4, 5])

In [79]:
a3[1,:,1] #2nd 2d array, all rows and 2nd column

array([10, 13, 16])

In [80]:
a3[2,1:,1:] #3rd 2d array, 2nd row and 2nd column onwards

array([[22, 23],
       [25, 26]])

In [84]:
a3[::2,:2:2,::2] # all 2d arrays, 2nd row and 2nd column onwards

array([[[ 0,  2]],

       [[18, 20]]])

Iteration in numpy arrays

In [85]:
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [88]:
for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


Reshaping

In [89]:
#transpose
np.transpose(a2) # transposes the array

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [90]:
#ravel any dimensional array into 1d
a3.ravel() # returns a 1d array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

Stacking

In [96]:
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12).reshape(3,4)

a6 = np.hstack((a4,a5)) # stacks the two arrays along the first axis

In [95]:
np.vstack((a4,a5)) # stacks the two arrays along the second axis

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

Spliting

In [100]:
np.hsplit(a6,2) # splits the array into 3 equal parts

[array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])]